/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";

const MOVEMENT_SPEED = 0.052;
// https://models.readyplayer.me/64fb1bd6a9fb106b21a9ef29.glb
export default function Avatar({
  avatarUrl = "3Dmodels/woman.glb",
  ...props
}) {
  const avatar = useRef();
  const position = useMemo(() => props.position, []);
  const group = useRef();
  const { scene } = useGLTF(avatarUrl);
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);

  const [animation, setAnimation] = useState("F_Dances_005")

  const { animations: danceAnimation } = useGLTF(
    "/animations/female_dance/F_Dances_005.glb"
  );

  const { actions } = useAnimations(danceAnimation, avatar);
  // console.log(actions);

  useEffect(() => {
    actions[animation].reset().fadeIn(0.32).play();
    return () => actions["m_Dances_002"]?.fadeOut(0.32);
  }, []);

  return (
    <group ref={group} {...props} position={position} dispose={null}>
      <primitive object={clone} ref={avatar} />
    </group>
  );
}

useGLTF.preload("3Dmodels/woman.glb");
useGLTF.preload("/animations/female_dance/m_Dances_002.glb");
