/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shindiego.ds (https://sketchfab.com/shindiego.ds)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/portal-first-experiment-1f34e82c35344508a6bf4104215119d3
title: Portal (First experiment)
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib';

export default function PortalExperiment(props) {
  const group = useRef()
  const { scene, animations } = useGLTF("/3Dmodels/portal_experiment.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // const { nodes, materials, animations } = useGLTF('/3Dmodels/portal_experiment.glb')
  const { actions } = useAnimations(animations, group)
 

  useEffect(() => {
    actions["Take 001"].reset().fadeIn(0.32).play();
    return () => actions["Take 001"]?.fadeOut(0.32);
  }, []);

  return (
    <group ref={group} {...props}  dispose={null}>
      <primitive object={scene}  />
    </group>
  )
}

useGLTF.preload('/3Dmodels/portal_experiment.glb')
